platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target 'SFAlertController_Example' do
  pod 'SFAlertController', :path => '../'

  target 'SFAlertController_Tests' do
    inherit! :search_paths

    
  end
end
